### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by alabamasearchandrescue-us** [lucaspal/flutter_critical_alert_permission_ios#1]
Flutter project won't build because this pub does not have null safety.

`Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:flutter_critical_alert_permission_ios

For solutions, see https://dart.dev/go/unsound-null-safety
`

**Comment by lucaspal** [comment]
Hey @alabamasearchandrescue-us thanks for raising this. 
I migrated to null safety in the last version `0.1.0`.

**Comment by alabamasearchandrescue-us** [comment]
> Hey @alabamasearchandrescue-us thanks for raising this. I migrated to null safety in the last version `0.1.0`.

THANK YOU!!
